[package]
name = "htop"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version ="0.8.8", features = ["macros"]}
dotenv = "0.15.0"
sysinfo = "0.37.2"
tokio = { version = "1.48.0", features = ["full"] }
